// 1_BRONZE
USE SCHEMA MI_PROYECTO."1_BRONZE";

-- Pedidos
CREATE OR REPLACE TABLE BRZ_ORDERS AS
    SELECT *, CURRENT_TIMESTAMP()  AS _BRONZE_LOADED_AT, '0_STAGING.STG_ORDERS' AS _SOURCE_TABLE
    FROM MI_PROYECTO."0_STAGING".STG_ORDERS;

-- Clientes
CREATE OR REPLACE TABLE BRZ_CUSTOMERS AS
    SELECT *, CURRENT_TIMESTAMP() AS _BRONZE_LOADED_AT, '0_STAGING.STG_CUSTOMERS' AS _SOURCE_TABLE
    FROM MI_PROYECTO."0_STAGING".STG_CUSTOMERS;

-- Líneas de pedido
CREATE OR REPLACE TABLE BRZ_LINEITEM AS
    SELECT *, CURRENT_TIMESTAMP()  AS _BRONZE_LOADED_AT,'0_STAGING.STG_LINEITEM' AS _SOURCE_TABLE
    FROM MI_PROYECTO."0_STAGING".STG_LINEITEM;

select * from brz_lineitem;


-- NACIONES
CREATE OR REPLACE TABLE BRZ_NATIONS AS
    SELECT *, CURRENT_TIMESTAMP()  AS _BRONZE_LOADED_AT,'0_STAGING.STG_NATIONS' AS _SOURCE_TABLE
    FROM MI_PROYECTO."0_STAGING".STG_NATIONS;

-- REGIONES
CREATE OR REPLACE TABLE BRZ_REGIONS AS
    SELECT *, CURRENT_TIMESTAMP()  AS _BRONZE_LOADED_AT,'0_STAGING_REGIONS' AS _SOURCE_TABLE
    FROM MI_PROYECTO."0_STAGING".STG_REGIONS;

-- PART
CREATE OR REPLACE TABLE BRZ_PART AS
    SELECT *, CURRENT_TIMESTAMP()  AS _BRONZE_LOADED_AT,'0_STAGING_PARTS' AS _SOURCE_TABLE
    FROM MI_PROYECTO."0_STAGING".STG_PART;

-- PARTSUPP
CREATE OR REPLACE TABLE BRZ_PARTSUPP AS
    SELECT *, CURRENT_TIMESTAMP()  AS _BRONZE_LOADED_AT,'0_STAGING_PARTSUPP' AS _SOURCE_TABLE
    FROM MI_PROYECTO."0_STAGING".STG_PARTSUPP;

-- SUPLIER
CREATE OR REPLACE TABLE BRZ_SUPPLIER AS
    SELECT *, CURRENT_TIMESTAMP() AS _BRONZE_LOADED_AT, '0_STAGING_SUPPLIER' AS _SOURCE_TABLE
    FROM MI_PROYECTO."0_STAGING".STG_SUPPLIER;

