// Paso 4: MODELO MEDALLION

// feature Create Table .. AS SELECT
// Cuando se crea la tabla de esta forma, snow no guarda los datos fila a fila como en un excel. Los almacena en micro particiones:
// bloques de 50 a 500 MB comprimidos, organizados por columnas. Los datos se almacenan por columnas: sistema OLAP, mas rapido para 
// analytics

// 0_STAGING
-- Tabla de pedidos
CREATE OR REPLACE TABLE MI_PROYECTO."0_STAGING".STG_ORDERS AS
    SELECT*,CURRENT_TIMESTAMP() AS _LOADED_AT
    FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS;
    
-- Tabla de clientes
CREATE OR REPLACE TABLE STG_CUSTOMERS AS
    SELECT*,CURRENT_TIMESTAMP() AS _LOADED_AT
    FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER;

-- Tabla de líneas de pedido
CREATE OR REPLACE TABLE STG_LINEITEM AS
    SELECT*,CURRENT_TIMESTAMP() AS _LOADED_AT
    FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM;

CREATE OR REPLACE TABLE STG_NATIONS AS
    SELECT *,CURRENT_TIMESTAMP() AS _LOADED_AT
    FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION;

CREATE OR REPLACE TABLE STG_REGIONS AS
    SELECT *,CURRENT_TIMESTAMP() AS _LOADED_AT
    FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION;

CREATE OR REPLACE TABLE STG_PART AS
    SELECT *,CURRENT_TIMESTAMP() AS _LOADED_AT
    FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PART;

CREATE OR REPLACE TABLE STG_PARTSUPP AS
    SELECT *,CURRENT_TIMESTAMP() AS _LOADED_AT
    FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PARTSUPP;

CREATE OR REPLACE TABLE STG_SUPPLIER AS
    SELECT *,CURRENT_TIMESTAMP() AS _LOADED_AT
    FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.SUPPLIER;